server {
    listen 80;
    server_name localhost;

    # Nơi chứa code Vite sau khi npm run build
    root   /usr/share/nginx/html;
    index  index.html index.htm;

    # Cấu hình chính cho React Router (Single Page Application)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy các request `/api/` thẳng đến Backend Go
    location /api/ {
        # Đảm bảo chỉnh lại IP Backend nếu chạy khác docker network
        proxy_pass http://host.docker.internal:8080/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Cấu hình cache cho static files (tăng tốc độ tải trang)
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg|mp4|webm)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
